export const CONTRACT_FAILURE_CODES = Object.freeze({
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  AUTHENTICATION_INVALID: "AUTHENTICATION_INVALID",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INTEGER_NON_CANONICAL: "INTEGER_NON_CANONICAL",
  INTEGER_OUT_OF_RANGE: "INTEGER_OUT_OF_RANGE",
  CURSOR_CONFLICT: "CURSOR_CONFLICT",
  DATA_LOSS_RANGE_INVALID: "DATA_LOSS_RANGE_INVALID",
  DIGEST_CONFLICT: "DIGEST_CONFLICT",
  DIGEST_MISMATCH: "DIGEST_MISMATCH",
  FIELD_BOUND: "FIELD_BOUND",
  INVALID_DIGEST: "INVALID_DIGEST",
  JSON_CYCLIC_VALUE: "JSON_CYCLIC_VALUE",
  JSON_INVALID_UNICODE: "JSON_INVALID_UNICODE",
  JSON_NON_FINITE_NUMBER: "JSON_NON_FINITE_NUMBER",
  JSON_UNSAFE_NUMBER: "JSON_UNSAFE_NUMBER",
  JSON_UNSUPPORTED_VALUE: "JSON_UNSUPPORTED_VALUE",
  JSON_SYNTAX_ERROR: "JSON_SYNTAX_ERROR",
  SEMVER_INVALID: "SEMVER_INVALID",
  STALE_SESSION: "STALE_SESSION",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",
  UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
} as const);

export type ContractFailureCode =
  (typeof CONTRACT_FAILURE_CODES)[keyof typeof CONTRACT_FAILURE_CODES];

/** A contract failure whose code is stable across language bindings. */
export class ContractFailure extends Error {
  override readonly name = "ContractFailure";

  constructor(
    readonly code: ContractFailureCode,
    message: string,
  ) {
    super(message);
  }
}
